# Generated by Django 5.1.4 on 2024-12-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_blogpost_likes_comment_user_alter_comment_blog_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comments",
            new_name="content",
        ),
    ]
