# Generated by Django 5.1.4 on 2025-01-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
