# Generated by Django 5.1.4 on 2025-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_user_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_password",
            field=models.BooleanField(default=False),
        ),
    ]
