# Generated by Django 5.1.4 on 2025-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_user_reset_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forgot_password_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="forgot_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="reset_password",
            field=models.BooleanField(default=True),
        ),
    ]
