# Generated by Django 5.1.4 on 2025-01-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_user_forgot_password_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="reset_password",
            field=models.BooleanField(default=False),
        ),
    ]
