# Generated by Django 5.1.4 on 2025-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_alter_user_reset_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
